ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER dynamite IDENTIFIED BY dynamite1234;
GRANT CONNECT, RESOURCE TO dynamite;
ALTER USER dynamite DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;