-- [[ INDEX ]]

DROP TABLE "CHALLENGE_DAILY_RESULT";
DROP TABLE "CHALLENGE";
DROP TABLE "CHALLENGE_LIST";
DROP SEQUENCE SEQ_USER_CHALLENGE_NO;

DROP TABLE "RECIPE";

DROP TABLE "USER_HISTORY";
DROP TABLE "USER_SESSION";
DROP SEQUENCE SEQ_RECIPE_NO;
DROP SEQUENCE SEQ_HISTORY_NO;

-- 1. 일기 관련 테이블 생성
DROP TABLE "DIARY_WORKOUT";
DROP TABLE "DIARY_FOOD";

-- 2. 음식관련 테이블 생성
DROP TABLE "FOOD";
DROP SEQUENCE SEQ_FOOD_NO;

-- 3. 운동 관련테이블 생성
DROP TABLE "USER_WORKOUT";
DROP TABLE "WORKOUT";
DROP TABLE "WORKOUT_AN_TYPE";

DROP SEQUENCE SEQ_WORKOUT_NO;
DROP SEQUENCE SEQ_USER_WORKOUT_NO;

-- 4. 좋아요 관련 테이블 생성
DROP TABLE "LIKE";
DROP TABLE "LIKE_TYPE";

-- 5. 채팅 관련 테이블 생성
DROP TABLE "MESSAGE";
DROP TABLE "CHAT_ROOM_MEMBER";
DROP TABLE "CHAT_ROOM";
DROP SEQUENCE SEQ_MESSAGE_NO;
DROP SEQUENCE SEQ_CHAT_ROOM_NO;

-- 6. 게시판 관련 테이블 생성
DROP TABLE "BOARD";
DROP SEQUENCE SEQ_BOARD_NO;
DROP TABLE "BOARD_TYPE";

-- 7. 지도 관련 테이블 생성
DROP TABLE "FAVORITE_PLACES";
DROP TABLE "PLACE_IMG";

-- 8. 댓글 관련 테이블 생성 
DROP TABLE "REPLY";
DROP TABLE "REPLY_TYPE";
DROP SEQUENCE SEQ_REPLY_NO;

-- 9. 유저 관련 테이블 생성
DROP TABLE "USER_INFO"; 
DROP SEQUENCE SEQ_USER_NO;


--===========================================================================================================
-- 1-1. 유저 정보 생성

CREATE TABLE "USER_INFO" (
	"USER_NO"	NUMBER	CONSTRAINT PK_USER_INFO PRIMARY KEY,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"USER_PW"	VARCHAR2(400)		NOT NULL,
	"USER_EMAIL"	VARCHAR2(100)		NOT NULL,
	"USER_NICKNAME"	VARCHAR2(48)		NOT NULL,
	"USER_BD"	CHAR(8)		NULL,
	"USER_GENDER"	CHAR(1)		NULL,
	"USER_IMG"	VARCHAR2(500)		NULL,
	"USER_AUTHORITY"	CHAR(1)	DEFAULT 'U'	NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"DELETE_DT"	DATE		NULL,
	"USER_PROFILE_HEIGHT"	NUMBER		NULL,
	"USER_PROFILE_WEIGHT"	NUMBER		NULL
);

COMMENT ON COLUMN "USER_INFO"."USER_NO" IS '유저번호(SEQ_USER_NO)';
COMMENT ON COLUMN "USER_INFO"."USER_ID" IS '유저 아이디(UNIQUE KEY)';
COMMENT ON COLUMN "USER_INFO"."USER_PW" IS '유저 비밀번호';
COMMENT ON COLUMN "USER_INFO"."USER_EMAIL" IS '유저 이메일(UNIQUE KEY)';
COMMENT ON COLUMN "USER_INFO"."USER_NICKNAME" IS '유저 닉네임';
COMMENT ON COLUMN "USER_INFO"."USER_BD" IS '유저 생일';
COMMENT ON COLUMN "USER_INFO"."USER_GENDER" IS '유저성별 (M or  F)';
COMMENT ON COLUMN "USER_INFO"."USER_IMG" IS '유저 프로필 이미지 변경';
COMMENT ON COLUMN "USER_INFO"."USER_AUTHORITY" IS '유저 권한';
COMMENT ON COLUMN "USER_INFO"."CREATE_DT" IS '유저 가입일';
COMMENT ON COLUMN "USER_INFO"."DELETE_DT" IS '유저 탈퇴일';
COMMENT ON COLUMN "USER_INFO"."USER_PROFILE_HEIGHT" IS '유저 신장';
COMMENT ON COLUMN "USER_INFO"."USER_PROFILE_WEIGHT" IS '유저 체중';

CREATE SEQUENCE SEQ_USER_NO NOCACHE;

-- 유저 세션

CREATE TABLE "USER_SESSION" (
    "USER_NO"  NUMBER NOT NULL,
    "SESSION_UUID" VARCHAR(64) NULL,
    CONSTRAINT FK_USER_SESSION_USER FOREIGN KEY (USER_NO) REFERENCES USER_INFO(USER_NO)
);


COMMENT ON COLUMN "USER_SESSION"."USER_NO" IS '유저번호(SEQ_USER_NO)';
COMMENT ON COLUMN "USER_SESSION"."SESSION_UUID" IS '유저 세션 UUID';

-- 유저 히스토리

CREATE TABLE "USER_HISTORY" (
    "HISTORY_NO"  NUMBER CONSTRAINT PK_HISTORY_NO PRIMARY KEY,
    "USER_NO"  NUMBER NOT NULL,
    "LOGIN_DT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "LOGIN_AUTO" CHAR(1) DEFAULT 'N' NOT NULL, 
    "LOGIN_IP" CHAR(16) NULL,
    CONSTRAINT FK_USER_HISTORY_USER FOREIGN KEY (USER_NO) REFERENCES USER_INFO(USER_NO)
);

COMMENT ON COLUMN "USER_HISTORY"."HISTORY_NO" IS '히스토리번호(SEQ_HISOTRY_NO)';
COMMENT ON COLUMN "USER_HISTORY"."USER_NO" IS '유저번호(SEQ_USER_NO)';
COMMENT ON COLUMN "USER_HISTORY"."LOGIN_DT" IS '로그인시간';
COMMENT ON COLUMN "USER_HISTORY"."LOGIN_AUTO" IS '자동 로그인 여부 판단';
COMMENT ON COLUMN "USER_HISTORY"."LOGIN_IP" IS '유저IP(v4)';

CREATE SEQUENCE SEQ_HISTORY_NO NOCACHE;
-- ========================================================================================================


-- 2-1. PLACE_IMG 테이블
CREATE TABLE "PLACE_IMG" (
    "PLACE_API_ID" NUMBER CONSTRAINT PK_PLACE_IMG_API_ID PRIMARY KEY,
    "PLACE_NAME" VARCHAR2(200) NOT NULL,
    "PLACE_IMG" VARCHAR2(2000) NULL
);

COMMENT ON COLUMN "PLACE_IMG"."PLACE_API_ID" IS 'API ID';
COMMENT ON COLUMN "PLACE_IMG"."PLACE_NAME" IS '장소 이름';
COMMENT ON COLUMN "PLACE_IMG"."PLACE_IMG" IS '장소 이미지';

-- 2-2. PLACES 테이블
CREATE TABLE "FAVORITE_PLACES" (
    "FP_API_ID" NUMBER CONSTRAINT FK_FAVORITE_PLACES_FP_API_ID REFERENCES PLACE_IMG  ON DELETE CASCADE NOT NULL, -- API ID
    "USER_NO" NUMBER CONSTRAINT FK_FAVORITE_PLACES_USER_NO REFERENCES USER_INFO(USER_NO) ON DELETE CASCADE NOT NULL, -- 유저 번호 
    "FP_NAME" VARCHAR2(50) NOT NULL,                    -- 장소 이름
    "FP_LATITUDE" NUMBER NOT NULL,                      -- 위도
    "FP_LONGITUDE" NUMBER NOT NULL,                     -- 경도
    "FP_ADDRESS" VARCHAR2(300) NOT NULL,                -- 주소
    "FP_PHONE" VARCHAR2(20) NULL,                       -- 장소 전화번호
    "FP_MAJOR_CATEGORY" VARCHAR2(120) NULL,             -- 장소 대분류
    "FP_MINOR_CATEGORY" VARCHAR2(120) NULL              -- 장소 소분류
);

COMMENT ON COLUMN "FAVORITE_PLACES"."FP_API_ID" IS 'API ID';
COMMENT ON COLUMN "FAVORITE_PLACES"."USER_NO" IS '유저 번호';
COMMENT ON COLUMN "FAVORITE_PLACES"."FP_NAME" IS '장소 이름';
COMMENT ON COLUMN "FAVORITE_PLACES"."FP_LATITUDE" IS '위도';
COMMENT ON COLUMN "FAVORITE_PLACES"."FP_LONGITUDE" IS '경도';
COMMENT ON COLUMN "FAVORITE_PLACES"."FP_ADDRESS" IS '장소 주소';
COMMENT ON COLUMN "FAVORITE_PLACES"."FP_PHONE" IS '장소 번호';
COMMENT ON COLUMN "FAVORITE_PLACES"."FP_MAJOR_CATEGORY" IS '장소 대분류';
COMMENT ON COLUMN "FAVORITE_PLACES"."FP_MINOR_CATEGORY" IS '장소 소분류';







--===========================================================================================================
-- 3-1. 채팅방 생성 
CREATE TABLE "CHAT_ROOM" (
	"ROOM_NO"	NUMBER	CONSTRAINT PK_CHAT_ROOM_NO PRIMARY KEY,
	"ROOM_NAME"	VARCHAR2(300)		NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CREATE_USER_NO"	NUMBER	CONSTRAINT FK_CHAT_ROOM_USER_NO REFERENCES USER_INFO(USER_NO) ON DELETE CASCADE	NOT NULL
);

COMMENT ON COLUMN "CHAT_ROOM"."ROOM_NO" IS '방 번호 (시퀀스)';
COMMENT ON COLUMN "CHAT_ROOM"."ROOM_NAME" IS '방 이름';
COMMENT ON COLUMN "CHAT_ROOM"."CREATE_DT" IS '방 생성일';
COMMENT ON COLUMN "CHAT_ROOM"."CREATE_USER_NO" IS '방 개설자(SEQ_USER_NO)';

CREATE SEQUENCE SEQ_CHAT_ROOM_NO NOCACHE;


-- 3-2. 채팅방 멤버 생성 (멤버 탈퇴시에는 NULL 값으로, 채팅방 제거시에는 완전 삭제, 유저 방 나갈경우 NULL 처리)
CREATE TABLE "CHAT_ROOM_MEMBER" (
	"ROOM_NO"	NUMBER  CONSTRAINT FK_ROOM_MEMBER_CHAT_ROOM REFERENCES CHAT_ROOM(ROOM_NO) ON DELETE CASCADE	NOT NULL,
	"USER_NO"	NUMBER	CONSTRAINT FK_ROOM_MEMBER_USER REFERENCES USER_INFO(USER_NO) ON DELETE SET NULL,
    "LAST_READ_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,

    CONSTRAINT UQ_ROOM_MEMBER_ROOM_NO_USER_NO UNIQUE(ROOM_NO, USER_NO)
);

COMMENT ON COLUMN "CHAT_ROOM_MEMBER"."ROOM_NO" IS '방 번호 (시퀀스)';
COMMENT ON COLUMN "CHAT_ROOM_MEMBER"."USER_NO" IS '유저번호(SEQ_USER_NO)';
COMMENT ON COLUMN "CHAT_ROOM_MEMBER"."LAST_READ_TIME" IS '마지막 메시지 읽은 시간';

-- 3-3. 메시지 생성
CREATE TABLE "MESSAGE" (
	"MESSAGE_NO"	NUMBER CONSTRAINT PK_MESSAGE_NO PRIMARY KEY,
	"MESSAGE_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"SENDER_NO"	NUMBER CONSTRAINT FK_MES_SENDER_NO REFERENCES USER_INFO(USER_NO) ON DELETE SET NULL,
	"ROOM_NO"	NUMBER CONSTRAINT FK_MES_ROOM_NO REFERENCES CHAT_ROOM(ROOM_NO) ON DELETE CASCADE NOT NULL,
	"SEND_TIME"	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN "MESSAGE"."MESSAGE_NO" IS '메시지 번호(시퀀스)';
COMMENT ON COLUMN "MESSAGE"."MESSAGE_CONTENT" IS '메시지 내용';
COMMENT ON COLUMN "MESSAGE"."SENDER_NO" IS '유저번호(SEQ_USER_NO)';
COMMENT ON COLUMN "MESSAGE"."ROOM_NO" IS '방 번호 (시퀀스)';
COMMENT ON COLUMN "MESSAGE"."SEND_TIME" IS '송신 시간';

CREATE SEQUENCE SEQ_MESSAGE_NO NOCACHE;



-- 4-1. 게시판타입 생성
CREATE TABLE "BOARD_TYPE" (
	"TYPE_NO"	NUMBER		NOT NULL,
	"TYPE_NAME"	VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."TYPE_NO" IS '게시판 타입 번호';

COMMENT ON COLUMN "BOARD_TYPE"."TYPE_NAME" IS '게시판 타입';

ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY (
	"TYPE_NO"
);
-- 4-2. 게시판테이블 생성 -- 추후 챌린지타입번호 fk추가필요함.
CREATE TABLE "BOARD" (
    "BOARD_NO"      NUMBER CONSTRAINT PK_BOARD_NO PRIMARY KEY,
    "USER_NO"       NUMBER NOT NULL,
    "BOARD_TYPE"    NUMBER NOT NULL,
    "CHALLENGE_NO"  NUMBER,
    "BOARD_TITLE"   VARCHAR2(150) NOT NULL,
    "BOARD_CONTENT" VARCHAR2(4000) NOT NULL,
    "BOARD_CNT"     NUMBER DEFAULT 0 NOT NULL,
    "BOARD_ST"      CHAR(3) DEFAULT 'N' NOT NULL,
    "CREATE_DT"     DATE DEFAULT SYSDATE NOT NULL,
    "UPDATE_DT"     DATE DEFAULT SYSDATE,
    "BOARD_IMG"     VARCHAR2(4000),
    
    CONSTRAINT FK_BOARD_USER FOREIGN KEY (USER_NO) REFERENCES USER_INFO(USER_NO),
    CONSTRAINT CK_BOARD_TYPE CHECK ("BOARD_TYPE" IN (1, 2)), 
    CONSTRAINT CK_BOARD_STATUS CHECK ("BOARD_ST" IN ('N', 'Y'))
);

CREATE SEQUENCE SEQ_BOARD_NO NOCACHE;

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호(시퀀스)';
COMMENT ON COLUMN "BOARD"."USER_NO" IS '유저번호(SEQ_USER_NO)';
COMMENT ON COLUMN "BOARD"."BOARD_TYPE" IS '게시판 타입 번호 (CHECK 1)';
COMMENT ON COLUMN "BOARD"."CHALLENGE_NO" IS '챌린지번호 (챌린지 아니면 NULL)';
COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';
COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';
COMMENT ON COLUMN "BOARD"."BOARD_CNT" IS '조회수';
COMMENT ON COLUMN "BOARD"."BOARD_ST" IS '게시글 상태(정상N 삭제Y)';
COMMENT ON COLUMN "BOARD"."CREATE_DT" IS '작성일';
COMMENT ON COLUMN "BOARD"."UPDATE_DT" IS '게시글 수정일';
COMMENT ON COLUMN "BOARD"."BOARD_IMG" IS '게시판 이미지';

-- 레시피

CREATE TABLE "RECIPE" (
   "RECIPE_NO"   NUMBER   CONSTRAINT PK_RECIPE_NO PRIMARY KEY,
   "USER_NO"  NUMBER NOT NULL,
   "RECIPE_TITLE"   VARCHAR2(200)      NOT NULL,
   "RECIPE_INGREDIENT"   VARCHAR2(4000) NOT NULL,
   "RECIPE_CONTENT"   VARCHAR2(4000) NOT NULL,
    "RECIPE_PRICE" NUMBER NOT NULL,
    "RECIPE_COOKTIME" VARCHAR2(30),
   "RECIPE_CAL" NUMBER NOT NULL,
   "RECIPE_HYDRO"   NUMBER    NOT NULL,
   "RECIPE_PROTEIN" NUMBER    NOT NULL,
   "RECIPE_FAT"   NUMBER    NOT NULL,
   "RECIPE_SOD"   NUMBER    NOT NULL,
   "RECIPE_FIBER"   NUMBER    NOT NULL,
   "RECIPE_CNT"   NUMBER    NOT NULL,
   "RECIPE_ST"       CHAR(3)   DEFAULT 'N' NOT NULL,
   "RECIPE_CREATE_DT"   DATE DEFAULT SYSDATE NOT NULL,
    "RECIPE_UPDATE_DT"   DATE DEFAULT SYSDATE  NULL,
    "RECIPE_IMG"   VARCHAR2(4000)   NULL,
    "RECIPE_URL"   VARCHAR2(4000)   NULL,
    
    CONSTRAINT FK_RECIPE_USER FOREIGN KEY (USER_NO) REFERENCES USER_INFO(USER_NO)
);

CREATE SEQUENCE SEQ_RECIPE_NO NOCACHE;

COMMENT ON COLUMN "RECIPE"."RECIPE_NO" IS '레시피 번호(시퀀스)';
COMMENT ON COLUMN "RECIPE"."USER_NO" IS '유저번호(SEQ_USER_NO)';
COMMENT ON COLUMN "RECIPE"."RECIPE_TITLE" IS '레시피 제목';
COMMENT ON COLUMN "RECIPE"."RECIPE_INGREDIENT" IS '레시피 재료';
COMMENT ON COLUMN "RECIPE"."RECIPE_CAL" IS '레시피 칼로리';
COMMENT ON COLUMN "RECIPE"."RECIPE_HYDRO" IS '총 탄수화물';
COMMENT ON COLUMN "RECIPE"."RECIPE_PROTEIN" IS '총 단백질';
COMMENT ON COLUMN "RECIPE"."RECIPE_FAT" IS '총 지방';
COMMENT ON COLUMN "RECIPE"."RECIPE_SOD" IS '총 나트륨';
COMMENT ON COLUMN "RECIPE"."RECIPE_FIBER" IS '총 식이섬유';
COMMENT ON COLUMN "RECIPE"."RECIPE_CNT" IS '레시피 조회수';
COMMENT ON COLUMN "RECIPE"."RECIPE_ST" IS '레시피 상태(정상N 삭제Y)';
COMMENT ON COLUMN "RECIPE"."RECIPE_CREATE_DT" IS '레시피 작성일';
COMMENT ON COLUMN "RECIPE"."RECIPE_UPDATE_DT" IS '레시피 수정일';
COMMENT ON COLUMN "RECIPE"."RECIPE_IMG" IS '레시피 이미지';
COMMENT ON COLUMN "RECIPE"."RECIPE_URL" IS '조리영상 URL';

-- 5-1. 좋아요유형 테이블
CREATE TABLE "LIKE_TYPE" (
    "LIKE_TYPE_NO" NUMBER CONSTRAINT PK_LIKE_TYPE_NO PRIMARY KEY,
    "LIKE_TYPE"    VARCHAR2(48) NOT NULL
);

COMMENT ON COLUMN "LIKE_TYPE"."LIKE_TYPE_NO" IS '좋아요 유형 번호';
COMMENT ON COLUMN "LIKE_TYPE"."LIKE_TYPE" IS '좋아요 유형';


-- 5-2. 좋아요 테이블
CREATE TABLE "LIKE" (
    USER_NO NUMBER NOT NULL,              
    LIKE_TYPE_NO NUMBER NOT NULL,        
    LIKE_TARGET_NO NUMBER NOT NULL,      
    CONSTRAINT PK_LIKE PRIMARY KEY (USER_NO, LIKE_TYPE_NO, LIKE_TARGET_NO),
    CONSTRAINT FK_LIKE_TO_LIKE_TYPE FOREIGN KEY (LIKE_TYPE_NO) REFERENCES LIKE_TYPE (LIKE_TYPE_NO), 
    CONSTRAINT FK_LIKE_TO_USER FOREIGN KEY (USER_NO) REFERENCES USER_INFO (USER_NO) 
    
);

COMMENT ON COLUMN "LIKE"."USER_NO" IS '유저번호(SEQ_USER_NO)';
COMMENT ON COLUMN "LIKE"."LIKE_TYPE_NO" IS '좋아요 유형 번호';
COMMENT ON COLUMN "LIKE"."LIKE_TARGET_NO" IS '좋아요 대상의 번호';


-- 6.1 운동통계 타입
CREATE TABLE "WORKOUT_AN_TYPE" (
	"WORKOUT_AN_TYPE_NO"	NUMBER	CONSTRAINT PK_WORKOUT_TYPE PRIMARY KEY,
	"WORKOUT_AN_TYPE_NAME"	VARCHAR2(120) NOT NULL
);

COMMENT ON COLUMN "WORKOUT_AN_TYPE"."WORKOUT_AN_TYPE_NO" IS '운동 통계 타입 번호';
COMMENT ON COLUMN "WORKOUT_AN_TYPE"."WORKOUT_AN_TYPE_NAME" IS '통계 타입 이름';


-- 6.2 운동테이블 
CREATE TABLE "WORKOUT" (
	"WORKOUT_NO" NUMBER CONSTRAINT PK_WORKOUT_NO PRIMARY KEY,
	"WORKOUT_NAME" VARCHAR2(120) NOT NULL,
	"WORKOUT_TYPE" NUMBER NOT NULL,
	"WORKOUT_CLASS"	VARCHAR(30)	NOT NULL,
	"WORKOUT_MET" NUMBER	NOT NULL,
	"WORKOUT_AN_TYPE_NO" NUMBER NOT NULL,
	"WORKOUT_CNT" NUMBER DEFAULT 0 NOT NULL,
     CONSTRAINT FK_WORKOUT_AN_TYPE_NO FOREIGN KEY (WORKOUT_AN_TYPE_NO) REFERENCES WORKOUT_AN_TYPE (WORKOUT_AN_TYPE_NO)
    
);

CREATE SEQUENCE SEQ_WORKOUT_NO NOCACHE;

COMMENT ON COLUMN "WORKOUT"."WORKOUT_NO" IS '시퀀스';
COMMENT ON COLUMN "WORKOUT"."WORKOUT_NAME" IS '운동명';
COMMENT ON COLUMN "WORKOUT"."WORKOUT_TYPE" IS '측정 분류 (시간, 거리)';
COMMENT ON COLUMN "WORKOUT"."WORKOUT_CLASS" IS '운동 분류';
COMMENT ON COLUMN "WORKOUT"."WORKOUT_MET" IS '단위 체중당 소모 칼로리';
COMMENT ON COLUMN "WORKOUT"."WORKOUT_AN_TYPE_NO" IS '운동 통계 타입 번호';
COMMENT ON COLUMN "WORKOUT"."WORKOUT_CNT" IS '운동 조회수';

-- 6.3 유저 운동일지
CREATE TABLE "USER_WORKOUT" (
	"USER_WORKOUT_NO"	NUMBER	CONSTRAINT PK_USER_WORKOUT_NO PRIMARY KEY NOT NULL,
	"USER_NO"	NUMBER	CONSTRAINT FK_USER_WORKOUT_USER_NO REFERENCES USER_INFO	NOT NULL,
	"WORKOUT_NO"	NUMBER	CONSTRAINT FK_USER_WORKOUT_WORKOUT_NO REFERENCES WORKOUT NOT NULL,
	"USER_WEIGHT"	VARCHAR(64)		NULL,
	"WORKOUT_TIME"	NUMBER		NOT NULL,
	"WORKOUT_DISTANCE"	NUMBER DEFAULT NULL,
	"WORKOUT_DATE"	VARCHAR2(30)	DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD')	NOT NULL,
	"WORKOUT_CAL"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "USER_WORKOUT"."USER_WORKOUT_NO" IS '운동일지 번호';
COMMENT ON COLUMN "USER_WORKOUT"."USER_NO" IS '유저번호(SEQ_USER_NO)';
COMMENT ON COLUMN "USER_WORKOUT"."WORKOUT_NO" IS '시퀀스';
COMMENT ON COLUMN "USER_WORKOUT"."USER_WEIGHT" IS '유저 세션 UUID';
COMMENT ON COLUMN "USER_WORKOUT"."WORKOUT_TIME" IS '운동 시간(분)';
COMMENT ON COLUMN "USER_WORKOUT"."WORKOUT_DISTANCE" IS '운동 거리(KM)';
COMMENT ON COLUMN "USER_WORKOUT"."WORKOUT_DATE" IS '무조건 당일';
COMMENT ON COLUMN "USER_WORKOUT"."WORKOUT_CAL" IS '운동당 칼로리 소모량';

CREATE SEQUENCE SEQ_USER_WORKOUT_NO;

-- 7. 음식테이블
CREATE TABLE "FOOD" (
	"FOOD_NO"	NUMBER	CONSTRAINT PK_FOOD_NO PRIMARY KEY,
	"FOOD_NAME"	VARCHAR(120) NOT NULL,
	"FOOD_TYPE"	VARCHAR(120) DEFAULT '해당없음'	NOT NULL,
	"FOOD_CAL"	NUMBER	DEFAULT 0	NOT NULL,
	"FOOD_PROTEIN"	NUMBER	DEFAULT 0	NOT NULL,
	"FOOD_FAT"	NUMBER	DEFAULT 0	NOT NULL,
	"FOOD_HYDRO" NUMBER	DEFAULT 0	NOT NULL,
	"FOOD_SUGAR" NUMBER	DEFAULT 0	NOT NULL,
	"FOOD_FIBER" NUMBER	DEFAULT 0	NOT NULL,
	"FOOD_SOD" NUMBER	DEFAULT 0	NOT NULL,
	"FOOD_COL" NUMBER	DEFAULT 0	NOT NULL,
	"FOOD_SAT_FAT" NUMBER DEFAULT 0	NOT NULL,
	"FOOD_TRANS_FAT" NUMBER	DEFAULT 0	NOT NULL,
	"FOOD_WEIGHT" NUMBER DEFAULT 0	NOT NULL,
	"FOOD_MANUFACTURE" VARCHAR2(120)	DEFAULT '해당없음' NULL,
	"FOOD_CNT" NUMBER DEFAULT 0	NOT NULL
);

CREATE SEQUENCE SEQ_FOOD_NO NOCACHE;

COMMENT ON COLUMN "FOOD"."FOOD_NO" IS '시퀀스';
COMMENT ON COLUMN "FOOD"."FOOD_NAME" IS '식품명';
COMMENT ON COLUMN "FOOD"."FOOD_TYPE" IS '식품 분류';
COMMENT ON COLUMN "FOOD"."FOOD_CAL" IS '식품의 칼로리';
COMMENT ON COLUMN "FOOD"."FOOD_PROTEIN" IS '단백질';
COMMENT ON COLUMN "FOOD"."FOOD_FAT" IS '지방';
COMMENT ON COLUMN "FOOD"."FOOD_HYDRO" IS '탄수화물';
COMMENT ON COLUMN "FOOD"."FOOD_SUGAR" IS '당류';
COMMENT ON COLUMN "FOOD"."FOOD_FIBER" IS '식이섬유';
COMMENT ON COLUMN "FOOD"."FOOD_SOD" IS '나트륨';
COMMENT ON COLUMN "FOOD"."FOOD_COL" IS '콜레스테롤';
COMMENT ON COLUMN "FOOD"."FOOD_SAT_FAT" IS '포화지방산';
COMMENT ON COLUMN "FOOD"."FOOD_TRANS_FAT" IS '트랜스지방산';
COMMENT ON COLUMN "FOOD"."FOOD_WEIGHT" IS '식품중량';
COMMENT ON COLUMN "FOOD"."FOOD_MANUFACTURE" IS '제조사명';
COMMENT ON COLUMN "FOOD"."FOOD_CNT" IS '조회수';

--8.1 운동관련 일기 테이블
CREATE TABLE DIARY_WORKOUT (
    BOARD_NO NUMBER NOT NULL, 
    WORKOUT_NO NUMBER NOT NULL,
    WORKOUT_DURATION NUMBER, 
    CALORIES_BURNED NUMBER,
    CONSTRAINT PK_DIARY_WORKOUT PRIMARY KEY (BOARD_NO, WORKOUT_NO),
    CONSTRAINT FK_BOARD FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO),
    CONSTRAINT FK_WORKOUT FOREIGN KEY (WORKOUT_NO) REFERENCES WORKOUT(WORKOUT_NO)
);

COMMENT ON COLUMN "DIARY_WORKOUT"."BOARD_NO" IS '게시글 번호(시퀀스)';

COMMENT ON COLUMN "DIARY_WORKOUT"."WORKOUT_NO" IS '시퀀스';

--8.2 음식관련 일기 테이블
CREATE TABLE "DIARY_FOOD" (
	"BOARD_NO" NUMBER NOT NULL,
	"FOOD_NO" NUMBER NOT NULL,
    SERVING_SIZE NUMBER, 
    CALORIES_INTAKE NUMBER,
    CONSTRAINT PK_DIARY_FOOD PRIMARY KEY (BOARD_NO, FOOD_NO),
    CONSTRAINT FK_BOARD_NO FOREIGN KEY (BOARD_NO) REFERENCES BOARD(BOARD_NO),
    CONSTRAINT FK_FOOD_NO FOREIGN KEY (FOOD_NO) REFERENCES FOOD(FOOD_NO)
);

COMMENT ON COLUMN "DIARY_FOOD"."BOARD_NO" IS '게시글 번호(시퀀스)';

COMMENT ON COLUMN "DIARY_FOOD"."FOOD_NO" IS '시퀀스';

-- 9.1 타겟 타입 번호 테이블

CREATE TABLE "REPLY_TYPE"(
	"REPLY_TYPE_NO" NUMBER CONSTRAINT PK_REPLY_TYPE_NO PRIMARY KEY,
	"REPLY_TYPE" VARCHAR2(40) NOT NULL
);

COMMENT ON COLUMN "REPLY_TYPE"."REPLY_TYPE_NO" IS '게시글 타입 번호 ';
COMMENT ON COLUMN "REPLY_TYPE"."REPLY_TYPE" IS '게시글 타입 이름 ';

CREATE TABLE "REPLY"(
	"REPLY_NO" NUMBER CONSTRAINT PK_REPLY_NO PRIMARY KEY,
	"USER_NO" NUMBER CONSTRAINT FK_REPLY_USER_NO REFERENCES USER_INFO(USER_NO) NOT NULL,
	"REPLY_TYPE_NO" NUMBER CONSTRAINT FK_REPLY_REPLY_TYPE_NO REFERENCES REPLY_TYPE(REPLY_TYPE_NO) NOT NULL,
	"REPLY_TARGET_NO" NUMBER NOT NULL,
	"REPLY_DT" DATE DEFAULT SYSDATE NOT NULL,
	"REPLY_CONTENT" VARCHAR2(300) NOT NULL,
	"REPLY_ST" CHAR(1) DEFAULT 'N' NOT NULL,
	"PARENT_NO" NUMBER NULL,
	"REPLY_STAR" NUMBER NULL
);

CREATE SEQUENCE SEQ_REPLY_NO NOCACHE;

COMMENT ON COLUMN "REPLY"."REPLY_NO" IS '댓글번호(시퀀스)';
COMMENT ON COLUMN "REPLY"."USER_NO" IS '댓글 작성자';
COMMENT ON COLUMN "REPLY"."REPLY_TYPE_NO" IS '댓글 타입 번호';
COMMENT ON COLUMN "REPLY"."REPLY_TARGET_NO" IS '댓글 대상 번호';
COMMENT ON COLUMN "REPLY"."REPLY_DT" IS '댓글 작성시간';
COMMENT ON COLUMN "REPLY"."REPLY_CONTENT" IS '댓글 내용';
COMMENT ON COLUMN "REPLY"."REPLY_ST" IS '댓글 상태';
COMMENT ON COLUMN "REPLY"."PARENT_NO" IS '부모 댓글 번호';
COMMENT ON COLUMN "REPLY"."REPLY_STAR" IS '별점 점수 ';

-- 10.1 챌린지 리스트
CREATE TABLE "CHALLENGE_LIST" (
	"CHALLENGE_NO"	NUMBER		NOT NULL,
	"CHALLENGE_LENGTH"	NUMBER		NOT NULL,
	"CHALLENGE_PIC"	VARCHAR2(100)		NOT NULL,
	"CHALLENGE_NAME"	VARCHAR2(60)		NOT NULL
);

COMMENT ON COLUMN "CHALLENGE_LIST"."CHALLENGE_NO" IS '챌린지번호';
COMMENT ON COLUMN "CHALLENGE_LIST"."CHALLENGE_LENGTH" IS '챌린지기간';
COMMENT ON COLUMN "CHALLENGE_LIST"."CHALLENGE_PIC" IS '챌린지아이콘그림';
COMMENT ON COLUMN "CHALLENGE_LIST"."CHALLENGE_NAME" IS '챌린지한글이름';

ALTER TABLE "CHALLENGE_LIST" ADD CONSTRAINT "PK_CHALLENGE_LIST" PRIMARY KEY("CHALLENGE_NO");

-- 10.2 챌린지(개인이 참여한 챌린지 정보)

CREATE TABLE "CHALLENGE" (
	"USER_CHALLENGE_NO"	NUMBER	NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"CHALLENGE_NO"	NUMBER		NOT NULL,
	"CHALLENGE_SECESSION"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"CHALLENGE_RESULT"	NUMBER	DEFAULT 0	NULL,
	"CHALLENGE_START_DAY"	DATE	DEFAULT SYSDATE	NOT NULL
);


COMMENT ON COLUMN "CHALLENGE"."USER_CHALLENGE_NO" IS '개인챌린지번호(SEQ)';
COMMENT ON COLUMN "CHALLENGE"."USER_NO" IS '유저번호(SEQ_USER_NO)';
COMMENT ON COLUMN "CHALLENGE"."CHALLENGE_NO" IS '챌린지번호';
COMMENT ON COLUMN "CHALLENGE"."CHALLENGE_SECESSION" IS '활성화/비활성화 N/Y';
COMMENT ON COLUMN "CHALLENGE"."CHALLENGE_RESULT" IS '챌린지수행결과(미완료 0, 완료 1)';

COMMENT ON COLUMN "CHALLENGE"."CHALLENGE_START_DAY" IS '챌린지시작일';
ALTER TABLE "CHALLENGE" ADD CONSTRAINT "PK_CHALLENGE" PRIMARY KEY ("USER_CHALLENGE_NO");
ALTER TABLE "CHALLENGE" ADD CONSTRAINT "FK_USER_INFO_TO_CHALLENGE_1" FOREIGN KEY (
	USER_NO
)
REFERENCES "USER_INFO" (
	USER_NO
);

ALTER TABLE "CHALLENGE" ADD CONSTRAINT "FK_CHALLENGE_LIST_TO_CHALLENGE_1" FOREIGN KEY (CHALLENGE_NO)
REFERENCES "CHALLENGE_LIST"(CHALLENGE_NO);

CREATE SEQUENCE SEQ_USER_CHALLENGE_NO NOCACHE;



-- 10.3 일일첼린지 결과

CREATE TABLE "CHALLENGE_DAILY_RESULT" (
	"DAILY_RESULT"	NUMBER	DEFAULT 0	NOT NULL,
	"CHALLENGE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"USER_CHALLENGE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "CHALLENGE_DAILY_RESULT"."DAILY_RESULT" IS '실패(0)';
COMMENT ON COLUMN "CHALLENGE_DAILY_RESULT"."CHALLENGE_DATE" IS '챌린지 수행일';
COMMENT ON COLUMN "CHALLENGE_DAILY_RESULT"."USER_CHALLENGE_NO" IS '개인챌린지번호(SEQ)';
ALTER TABLE "CHALLENGE_DAILY_RESULT" ADD CONSTRAINT "FK_CHALLENGE_TO_CHALLENGE_DAILY_RESULT_1" FOREIGN KEY (
	"USER_CHALLENGE_NO"
)
REFERENCES "CHALLENGE" (
	"USER_CHALLENGE_NO"
);

