-- [[ INDEX ]]
-- 1. 장소 정보 조회 
    DROP SEQUENCE  SEQ_FP_NO;
	DROP TABLE FAVORITE_PLACE;
    
-- ========================================================================================================

-- 1. PLACES 테이블
CREATE TABLE FAVORITE_PLACE (
    FP_ID NUMBER CONSTRAINT PK_FAVORITE_PLACE PRIMARY KEY,        
    FP_NAME VARCHAR2(50) NOT NULL,  
    FP_LATITUDE NUMBER(10, 7) NOT NULL,  
    FP_LONGITUDE NUMBER(10, 7) NOT NULL,
    FP_ADDRESS VARCHAR2(255) NOT NULL,
    FP_PHONE VARCHAR2(20) NOT NULL
);
COMMENT ON COLUMN "FAVORITE_PLACE"."FP_ID" IS '장소 ID';
COMMENT ON COLUMN "FAVORITE_PLACE"."FP_NAME" IS '장소 이름';
COMMENT ON COLUMN "FAVORITE_PLACE"."FP_LATITUDE" IS '위도';
COMMENT ON COLUMN "FAVORITE_PLACE"."FP_LONGITUDE" IS '경도';
COMMENT ON COLUMN "FAVORITE_PLACE"."FP_ADDRESS" IS '장소 주소';
COMMENT ON COLUMN "FAVORITE_PLACE"."FP_PHONE" IS '장소 번호';

CREATE SEQUENCE SEQ_FP_NO NOCACHE;