-- [[ INDEX ]]

-- 1. 채팅 관련 테이블 생성
DROP TABLE "MESSAGE";
DROP TABLE "CHAT_ROOM_MEMBER";
DROP TABLE "CHAT_ROOM";
DROP SEQUENCE SEQ_MESSAGE_NO;
DROP SEQUENCE SEQ_CHAT_ROOM_NO;

-- 2. 게시판 관련 테이블 생성
DROP TABLE "BOARD";
DROP SEQUENCE SEQ_BOARD_NO;
DROP TABLE "BOARD_TYPE";

-- 3. 지도 관련 테이블 생성
DROP TABLE "FAVORITE_PLACES";

-- 4. 유저 관련 테이블 생성
DROP TABLE "USER_INFO"; 
DROP SEQUENCE SEQ_USER_NO;

--===========================================================================================================
-- 1-1. 유저 정보 생성

CREATE TABLE "USER_INFO" (
	"USER_NO"	NUMBER	CONSTRAINT PK_USER_INFO PRIMARY KEY,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"USER_PW"	VARCHAR2(400)		NOT NULL,
	"USER_EMAIL"	VARCHAR2(100)		NOT NULL,
	"USER_NICKNAME"	VARCHAR2(48)		NOT NULL,
	"USER_BD"	CHAR(8)		NULL,
	"USER_GENDER"	CHAR(1)		NULL,
	"USER_IMG"	VARCHAR2(500)		NULL,
	"USER_AUTHORITY"	CHAR(1)	DEFAULT 'U'	NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"DELETE_DT"	DATE		NULL,
	"USER_PROFILE_HEIGHT"	NUMBER		NULL,
	"USER_PROFILE_WEIGHT"	NUMBER		NULL
);

COMMENT ON COLUMN "USER_INFO"."USER_NO" IS '유저번호(SEQ_USER_NO)';
COMMENT ON COLUMN "USER_INFO"."USER_ID" IS '유저 아이디(UNIQUE KEY)';
COMMENT ON COLUMN "USER_INFO"."USER_PW" IS '유저 비밀번호';
COMMENT ON COLUMN "USER_INFO"."USER_EMAIL" IS '유저 이메일(UNIQUE KEY)';
COMMENT ON COLUMN "USER_INFO"."USER_NICKNAME" IS '유저 닉네임';
COMMENT ON COLUMN "USER_INFO"."USER_BD" IS '유저 생일';
COMMENT ON COLUMN "USER_INFO"."USER_GENDER" IS '유저성별 (M or  F)';
COMMENT ON COLUMN "USER_INFO"."USER_IMG" IS '유저 프로필 이미지 변경';
COMMENT ON COLUMN "USER_INFO"."USER_AUTHORITY" IS '유저 권한';
COMMENT ON COLUMN "USER_INFO"."CREATE_DT" IS '유저 가입일';
COMMENT ON COLUMN "USER_INFO"."DELETE_DT" IS '유저 탈퇴일';
COMMENT ON COLUMN "USER_INFO"."USER_PROFILE_HEIGHT" IS '유저 신장';
COMMENT ON COLUMN "USER_INFO"."USER_PROFILE_WEIGHT" IS '유저 체중';

CREATE SEQUENCE SEQ_USER_NO NOCACHE;


-- ========================================================================================================
-- 2-1. PLACES 테이블
CREATE TABLE "FAVORITE_PLACES" (
    "FP_API_ID" NUMBER CONSTRAINT PK_FAVORITE_PLACES_API_ID PRIMARY KEY, -- API ID
    "USER_NO" NUMBER CONSTRAINT PK_FAVORITE_PLACES_USER_NO REFERENCES USER_INFO(USER_NO) ON DELETE CASCADE NOT NULL,
    "FP_NAME" VARCHAR2(50) NOT NULL,                    -- 장소 이름
    "FP_LATITUDE" NUMBER NOT NULL,                      -- 위도
    "FP_LONGITUDE" NUMBER NOT NULL,                     -- 경도
    "FP_ADDRESS" VARCHAR2(300) NOT NULL,                -- 주소
    "FP_PHONE" VARCHAR2(20) NOT NULL,                   -- 장소 전화번호
    "FP_MAJOR_CATEGORY" VARCHAR2(120) NULL,             -- 장소 대분류
    "FP_MINOR_CATEGORY" VARCHAR2(120) NULL              -- 장소 소분류
);

COMMENT ON COLUMN "FAVORITE_PLACES"."FP_API_ID" IS 'API ID';
COMMENT ON COLUMN "FAVORITE_PLACES"."FP_NAME" IS '장소 이름';
COMMENT ON COLUMN "FAVORITE_PLACES"."FP_LATITUDE" IS '위도';
COMMENT ON COLUMN "FAVORITE_PLACES"."FP_LONGITUDE" IS '경도';
COMMENT ON COLUMN "FAVORITE_PLACES"."FP_ADDRESS" IS '장소 주소';
COMMENT ON COLUMN "FAVORITE_PLACES"."FP_PHONE" IS '장소 번호';
COMMENT ON COLUMN "FAVORITE_PLACES"."FP_MAJOR_CATEGORY" IS '장소 대분류';
COMMENT ON COLUMN "FAVORITE_PLACES"."FP_MINOR_CATEGORY" IS '장소 소분류';




--===========================================================================================================
-- 3-1. 채팅방 생성 
CREATE TABLE "CHAT_ROOM" (
	"ROOM_NO"	NUMBER	CONSTRAINT PK_CHAT_ROOM_NO PRIMARY KEY,
	"ROOM_NAME"	VARCHAR2(300)		NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"CREATE_USER_NO"	NUMBER	CONSTRAINT FK_CHAT_ROOM_USER_NO REFERENCES USER_INFO(USER_NO) ON DELETE CASCADE	NOT NULL
);

COMMENT ON COLUMN "CHAT_ROOM"."ROOM_NO" IS '방 번호 (시퀀스)';
COMMENT ON COLUMN "CHAT_ROOM"."ROOM_NAME" IS '방 이름';
COMMENT ON COLUMN "CHAT_ROOM"."CREATE_DT" IS '방 생성일';
COMMENT ON COLUMN "CHAT_ROOM"."CREATE_USER_NO" IS '방 개설자(SEQ_USER_NO)';

CREATE SEQUENCE SEQ_CHAT_ROOM_NO NOCACHE;


-- 3-2. 채팅방 멤버 생성 (멤버 탈퇴시에는 NULL 값으로, 채팅방 제거시에는 완전 삭제, 유저 방 나갈경우 NULL 처리)
CREATE TABLE "CHAT_ROOM_MEMBER" (
	"ROOM_NO"	NUMBER  CONSTRAINT FK_ROOM_MEMBER_CHAT_ROOM REFERENCES CHAT_ROOM(ROOM_NO) ON DELETE CASCADE	NOT NULL,
	"USER_NO"	NUMBER	CONSTRAINT FK_ROOM_MEMBER_USER REFERENCES USER_INFO(USER_NO) ON DELETE SET NULL,
    "LAST_READ_TIME" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,

    CONSTRAINT UQ_ROOM_MEMBER_ROOM_NO_USER_NO UNIQUE(ROOM_NO, USER_NO)
);

COMMENT ON COLUMN "CHAT_ROOM_MEMBER"."ROOM_NO" IS '방 번호 (시퀀스)';
COMMENT ON COLUMN "CHAT_ROOM_MEMBER"."USER_NO" IS '유저번호(SEQ_USER_NO)';
COMMENT ON COLUMN "CHAT_ROOM_MEMBER"."LAST_READ_TIME" IS '마지막 메시지 읽은 시간';

-- 3-3. 메시지 생성
CREATE TABLE "MESSAGE" (
	"MESSAGE_NO"	NUMBER CONSTRAINT PK_MESSAGE_NO PRIMARY KEY,
	"MESSAGE_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"SENDER_NO"	NUMBER CONSTRAINT FK_MES_SENDER_NO REFERENCES USER_INFO(USER_NO) ON DELETE SET NULL,
	"ROOM_NO"	NUMBER CONSTRAINT FK_MES_ROOM_NO REFERENCES CHAT_ROOM(ROOM_NO) ON DELETE CASCADE NOT NULL,
	"SEND_TIME"	TIMESTAMP	DEFAULT CURRENT_TIMESTAMP NOT NULL
);

COMMENT ON COLUMN "MESSAGE"."MESSAGE_NO" IS '메시지 번호(시퀀스)';
COMMENT ON COLUMN "MESSAGE"."MESSAGE_CONTENT" IS '메시지 내용';
COMMENT ON COLUMN "MESSAGE"."SENDER_NO" IS '유저번호(SEQ_USER_NO)';
COMMENT ON COLUMN "MESSAGE"."ROOM_NO" IS '방 번호 (시퀀스)';
COMMENT ON COLUMN "MESSAGE"."SEND_TIME" IS '송신 시간';

CREATE SEQUENCE SEQ_MESSAGE_NO NOCACHE;



-- 4-1. 게시판타입 생성
CREATE TABLE "BOARD_TYPE" (
	"TYPE_NO"	NUMBER		NOT NULL,
	"TYPE_NAME"	VARCHAR2(10) NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."TYPE_NO" IS '게시판 타입 번호';

COMMENT ON COLUMN "BOARD_TYPE"."TYPE_NAME" IS '게시판 타입';

ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY (
	"TYPE_NO"
);
-- 4-2. 게시판테이블 생성 -- 추후 챌린지타입번호 fk추가필요함.
CREATE TABLE "BOARD" (
    "BOARD_NO"      NUMBER CONSTRAINT PK_BOARD_NO PRIMARY KEY,
    "USER_NO"       NUMBER NOT NULL,
    "BOARD_TYPE"    NUMBER NOT NULL,
    "CHALLENGE_NO"  NUMBER,
    "BOARD_TITLE"   VARCHAR2(150) NOT NULL,
    "BOARD_CONTENT" VARCHAR2(4000) NOT NULL,
    "BOARD_CNT"     NUMBER DEFAULT 0 NOT NULL,
    "BOARD_ST"      CHAR(3) DEFAULT 'N' NOT NULL,
    "CREATE_DT"     DATE DEFAULT SYSDATE NOT NULL,
    "UPDATE_DT"     DATE DEFAULT SYSDATE,
    "BOARD_IMG"     VARCHAR2(4000),
    
    CONSTRAINT FK_BOARD_USER FOREIGN KEY (USER_NO) REFERENCES USER_INFO(USER_NO),
    CONSTRAINT CK_BOARD_TYPE CHECK ("BOARD_TYPE" IN (1, 2)), 
    CONSTRAINT CK_BOARD_STATUS CHECK ("BOARD_ST" IN ('N', 'Y'))
);

CREATE SEQUENCE SEQ_BOARD_NO NOCACHE;

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호(시퀀스)';

COMMENT ON COLUMN "BOARD"."USER_NO" IS '유저번호(SEQ_USER_NO)';

COMMENT ON COLUMN "BOARD"."BOARD_TYPE" IS '게시판 타입 번호 (CHECK 1)';

COMMENT ON COLUMN "BOARD"."CHALLENGE_NO" IS '챌린지번호 (챌린지 아니면 NULL)';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."BOARD_CNT" IS '조회수';

COMMENT ON COLUMN "BOARD"."BOARD_ST" IS '게시글 상태(정상N 삭제Y)';

COMMENT ON COLUMN "BOARD"."CREATE_DT" IS '작성일';

COMMENT ON COLUMN "BOARD"."UPDATE_DT" IS '게시글 수정일';

COMMENT ON COLUMN "BOARD"."BOARD_IMG" IS '게시판 이미지';


