-- [[ INDEX ]]
-- 1. TYPE


     
-- 2. ESSEENTIAL
-- 2-1 TYPE 번호 
INSERT INTO "REPLY_TYPE" VALUES(1,'일반 게시글');
INSERT INTO "REPLY_TYPE" VALUES(2,'다이어트 레시피');
INSERT INTO "REPLY_TYPE" VALUES(3,'지도 상세');
INSERT INTO "REPLY_TYPE" VALUES(4,'음식 정보');

COMMIT;

-- 2-2. 게시판타입
INSERT INTO "BOARD_TYPE" ("TYPE_NO", "TYPE_NAME") VALUES (1, '일기');
INSERT INTO "BOARD_TYPE" ("TYPE_NO", "TYPE_NAME") VALUES (2, '챌린지');

COMMIT;

-- 2-3 좋아요 타입 
INSERT INTO LIKE_TYPE (LIKE_TYPE_NO, LIKE_TYPE) VALUES (1, '게시글');
INSERT INTO LIKE_TYPE (LIKE_TYPE_NO, LIKE_TYPE) VALUES (2, '댓글');
INSERT INTO LIKE_TYPE (LIKE_TYPE_NO, LIKE_TYPE) VALUES (3, '다이어트레시피');

COMMIT;

-- 2-4 운동통계타입
INSERT INTO WORKOUT_TYPE (WORKOUT_TYPE_NO, WORKOUT_TYPE_NAME) VALUES (1, '땅에서 거리 운동');
INSERT INTO WORKOUT_TYPE (WORKOUT_TYPE_NO, WORKOUT_TYPE_NAME) VALUES (2, '물에서 거리 운동');
INSERT INTO WORKOUT_TYPE (WORKOUT_TYPE_NO, WORKOUT_TYPE_NAME) VALUES (3, '가슴운동');
INSERT INTO WORKOUT_TYPE (WORKOUT_TYPE_NO, WORKOUT_TYPE_NAME) VALUES (4, '등운동');
INSERT INTO WORKOUT_TYPE (WORKOUT_TYPE_NO, WORKOUT_TYPE_NAME) VALUES (5, '배운동');
INSERT INTO WORKOUT_TYPE (WORKOUT_TYPE_NO, WORKOUT_TYPE_NAME) VALUES (6, '다리운동');
INSERT INTO WORKOUT_TYPE (WORKOUT_TYPE_NO, WORKOUT_TYPE_NAME) VALUES (7, '기타');

COMMIT;


    
-- ========================================================================================================

-- 2-1. 로그인 유저 임시 (현재 암호화 미적용상태)
                                                       -- a
INSERT INTO USER_INFO VALUES (SEQ_USER_NO.NEXTVAL, 'a','$2a$10$TitYxIQ8xBOuzRZ66qFJ2.KL5Ogup4FfYQmLQsJrhdAy3V4.XQa7a','test@test.com','불타는김밥','19900101','M',
                            '/resources/images/profile/user_img1.jpg','A', DEFAULT,NULL, 180,70);

                                                       -- b
INSERT INTO USER_INFO VALUES (SEQ_USER_NO.NEXTVAL, 'b','$2a$10$SWcZb6kgoAb3IGTDwgbWY.hZpaiLtQghcod85EwL66mwJlND3pJPe','test@test.com','불타는유저','19900101','M',
                            '/resources/images/profile/user_img1.jpg','U', DEFAULT,NULL, 180,70);

                                                       -- c
INSERT INTO USER_INFO VALUES (SEQ_USER_NO.NEXTVAL, 'c','$2a$10$KtM4eqNjJ0M8vYVvJ6g/duCcHUZwE20uQqMG/bP2GrvOZD0LJizIy','test@test.com','불타는감자','19900101','M',
                            '/resources/images/profile/user_img1.jpg','A', DEFAULT,NULL, 180,70);

                                                       -- d
INSERT INTO USER_INFO VALUES (SEQ_USER_NO.NEXTVAL, 'd','$2a$10$cIUV1bsJ6px76w56Xr2U0eHwlNoYU.d7PwjopwxEmZU9T9gZpzF.W','test@test.com','불타는주먹','19900101','M',
                            '/resources/images/profile/user_img1.jpg','A', DEFAULT,NULL, 180,70);

                                                       -- e
INSERT INTO USER_INFO VALUES (SEQ_USER_NO.NEXTVAL, 'e','$2a$10$BRAk2FIgUTQhA4gTU.WFJ.6PutM3OCiBmplgX/sw90hFT9xy161QC','test@test.com','불타는옥수수','19900101','M',
                            '/resources/images/profile/user_img1.jpg','A', DEFAULT,NULL, 180,70);

COMMIT;




-- 2-2 지도 이미지 추가
INSERT INTO "PLACE_IMG" VALUES(26307587 , 
't1.kakaocdn.net/thumb/T800x0.q50/?fname=http://t1.daumcdn.net/place/0DE3B91211874EEBA2B19D0E7967606A');

INSERT INTO "PLACE_IMG" VALUES(7983060 , 
't1.kakaocdn.net/thumb/T800x0.q50/?fname=http://t1.daumcdn.net/place/8F3B594E174D44AB9C4558D42A432488');

INSERT INTO "PLACE_IMG" VALUES(1684702238 , 
't1.kakaocdn.net/thumb/T800x0.q50/?fname=http://t1.daumcdn.net/place/C3C1E1B9396F44CA8A2CACF481FBD490');

INSERT INTO "PLACE_IMG" VALUES(677970364 , 
't1.kakaocdn.net/thumb/T800x0.q50/?fname=http://t1.kakaocdn.net/fiy_reboot/place/9DC984EF01DA433DBF3609735581BF10');

INSERT INTO "PLACE_IMG" VALUES(21801668 , 
't1.kakaocdn.net/thumb/T800x0.q50/?fname=http://t1.daumcdn.net/place/873F2429461C4FBEB19522DD1CAC3DB9');

COMMIT;

-- 2.2. 지도 즐겨찾기 추가
INSERT INTO FAVORITE_PLACES (FP_API_ID, USER_NO, FP_NAME, FP_LATITUDE, FP_LONGITUDE, FP_ADDRESS, FP_PHONE, FP_MAJOR_CATEGORY, FP_MINOR_CATEGORY)
VALUES (26307587, 1, '초록밭', 37.499582154338356, 127.05162512267073, '서울 강남구 대치동 921-2', '010-7677-9317', '음식점' , '샐러드');

COMMIT;



-- 2-3. 채팅방 데이터
INSERT INTO CHAT_ROOM VALUES(SEQ_CHAT_ROOM_NO.nextval, '채팅방1', DEFAULT, 1);

COMMIT;

-- 2-4. 채팅방 참가자 데이터 (3번째 파라미터 -> 현재 시간까지는 읽음)
INSERT INTO CHAT_ROOM_MEMBER VALUES(1,1, DEFAULT);  -- 채팅방 1번, 유저 1 추가 (생성자 본인도 참가자에 추가)
INSERT INTO CHAT_ROOM_MEMBER VALUES(1,2, DEFAULT);  -- 채팅방 1번, 유저 2 추가 

COMMIT;

-- 2-5. 메시지 생성
INSERT INTO "MESSAGE" VALUES(SEQ_MESSAGE_NO.nextval, 'ㅋㅌㅊㅋㅌㅊ', 1, 1, DEFAULT);            -- 1번 유저가, 1번방에서 메시지씀
INSERT INTO "MESSAGE" VALUES(SEQ_MESSAGE_NO.nextval, 'ㅋㅌㄷㄳㅍㅊ', 2, 1, DEFAULT);            -- 2번 유저가, 1번방에서 메시지씀
INSERT INTO "MESSAGE" VALUES(SEQ_MESSAGE_NO.nextval, 'ㅋㅡㅠㅜㅌㅊ', 1, 1, DEFAULT);            -- 1번 유저가, 1번방에서 메시지씀
INSERT INTO "MESSAGE" VALUES(SEQ_MESSAGE_NO.nextval, 'ㅋㅌㄷㄳㄷㄱㅌㅊ', 1, 1, DEFAULT);        -- 1번 유저가, 1번방에서 메시지씀

COMMIT;




-- 3-2. 일기 더미데이터 100개.

BEGIN
   FOR I IN 1..100 LOOP
      INSERT INTO BOARD(
             BOARD_NO, USER_NO, BOARD_TYPE, CHALLENGE_NO, 
          BOARD_TITLE, BOARD_CONTENT, BOARD_CNT, BOARD_ST, 
          CREATE_DT, UPDATE_DT, BOARD_IMG)
      VALUES( SEQ_BOARD_NO.NEXTVAL,
              2, 
              1,
              NULL,
              SEQ_BOARD_NO.CURRVAL || '번째 게시글',
              SEQ_BOARD_NO.CURRVAL || '번째 게시글 내용 입니다.',
              0, 'N', SYSDATE, SYSDATE, '/resources/images/logo.png'
      );
   END LOOP;
   COMMIT;
END;
/


-- 4. 댓글 추가

INSERT INTO "REPLY" 
VALUES (SEQ_REPLY_NO.NEXTVAL, 1, 1, 1, DEFAULT, '1번째 댓글입니다.', DEFAULT, NULL, NULL);

INSERT INTO "REPLY" 
VALUES (SEQ_REPLY_NO.NEXTVAL, 1, 1, 2, DEFAULT, '2번째 댓글입니다.', DEFAULT, NULL, NULL);

INSERT INTO "REPLY" 
VALUES (SEQ_REPLY_NO.NEXTVAL, 1, 1, 3, DEFAULT, '3번째 댓글입니다.', DEFAULT, NULL, NULL);

INSERT INTO "REPLY" 
VALUES (SEQ_REPLY_NO.NEXTVAL, 1, 3, 21801668, DEFAULT, '지도 상세 1번째 댓글입니다.', DEFAULT, NULL, 2);

INSERT INTO "REPLY"
VALUES (SEQ_REPLY_NO.NEXTVAL, 1, 3, 21801668, DEFAULT, '지도 상세 2번째 댓글입니다.', DEFAULT, NULL, 3);

COMMIT;


-- 4-2 좋아요
INSERT INTO "LIKE" (USER_NO, LIKE_TYPE_NO, LIKE_TARGET_NO)
VALUES (1, 1, 100);
INSERT INTO "LIKE" (USER_NO, LIKE_TYPE_NO, LIKE_TARGET_NO)
VALUES (1, 1, 99);
INSERT INTO "LIKE" (USER_NO, LIKE_TYPE_NO, LIKE_TARGET_NO)
VALUES (1, 1, 98);

COMMIT;

-- 5. 음식데이터 (임시)
INSERT INTO FOOD (FOOD_NO, FOOD_NAME, FOOD_TYPE, FOOD_CAL, FOOD_PROTEIN, FOOD_FAT, FOOD_HYDRO, FOOD_SUGAR, FOOD_FIBER, FOOD_SOD, FOOD_COL, FOOD_SAT_FAT, FOOD_TRANS_FAT, FOOD_WEIGHT, FOOD_MANUFACTURE, FOOD_CNT)
VALUES (SEQ_FOOD_NO.NEXTVAL, '33한체다치즈팝콘', '과자', 478, 9.34, 19.5, 66.2, 4.58, 0, 594, 11.9, 11.6, 0, 150, '대한푸드텍(주)', 0);

INSERT INTO FOOD (FOOD_NO, FOOD_NAME, FOOD_TYPE, FOOD_CAL, FOOD_PROTEIN, FOOD_FAT, FOOD_HYDRO, FOOD_SUGAR, FOOD_FIBER, FOOD_SOD, FOOD_COL, FOOD_SAT_FAT, FOOD_TRANS_FAT, FOOD_WEIGHT, FOOD_MANUFACTURE, FOOD_CNT)
VALUES (SEQ_FOOD_NO.NEXTVAL, 'CGV시그니처스위트팝콘', '과자', 529, 4.29, 28.57, 64.29, 22.86, 0, 221, 0, 7.14, 0, 70, '(주)제이앤이', 0);

INSERT INTO FOOD (FOOD_NO, FOOD_NAME, FOOD_TYPE, FOOD_CAL, FOOD_PROTEIN, FOOD_FAT, FOOD_HYDRO, FOOD_SUGAR, FOOD_FIBER, FOOD_SOD, FOOD_COL, FOOD_SAT_FAT, FOOD_TRANS_FAT, FOOD_WEIGHT, FOOD_MANUFACTURE, FOOD_CNT)
VALUES (SEQ_FOOD_NO.NEXTVAL, 'dardaby커널스슈퍼믹스팝콘', '과자', 473, 4, 20, 72.73, 34.55, 0, 182, 16.36, 9.09, 0, 55, '(주)제이앤이', 0);

COMMIT;
-- 6. 운동데이터(임시)
INSERT INTO WORKOUT (WORKOUT_NO, WORKOUT_NAME, WORKOUT_TYPE, WORKOUT_CLASS, WORKOUT_MET, WORKOUT_TYPE_NO, WORKOUT_CNT) VALUES (1, '바벨 스쿼트', 1, '근력', 6, 1, 100);
INSERT INTO WORKOUT (WORKOUT_NO, WORKOUT_NAME, WORKOUT_TYPE, WORKOUT_CLASS, WORKOUT_MET, WORKOUT_TYPE_NO, WORKOUT_CNT) VALUES (2, '다트', 1, '기타', 2.5, 1, 10);
INSERT INTO WORKOUT (WORKOUT_NO, WORKOUT_NAME, WORKOUT_TYPE, WORKOUT_CLASS, WORKOUT_MET, WORKOUT_TYPE_NO, WORKOUT_CNT) VALUES (3, '야구 캐치볼', 1, '기타', 2.5, 1, 200);
INSERT INTO WORKOUT (WORKOUT_NO, WORKOUT_NAME, WORKOUT_TYPE, WORKOUT_CLASS, WORKOUT_MET, WORKOUT_TYPE_NO, WORKOUT_CNT) VALUES (4, '당구', 1, '스포츠', 2.5, 1, 500);
COMMIT;

-- 7. 다이어리일기 음식 
INSERT INTO DIARY_FOOD (BOARD_NO, FOOD_NO)
VALUES (100, 1);

INSERT INTO DIARY_FOOD (BOARD_NO, FOOD_NO)
VALUES (99, 1);
COMMIT;

-- 8. 다이어리일기 운동

INSERT INTO DIARY_WORKOUT (BOARD_NO, WORKOUT_NO)
VALUES (100, 1);

INSERT INTO DIARY_WORKOUT (BOARD_NO, WORKOUT_NO)
VALUES (99, 2);

COMMIT;

