SELECT TRUNC(SYSDATE) FROM DUAL;

CREATE TABLE TEST_TABLE (
    TEST_1 DATE DEFAULT TRUNC(SYSDATE)
);

CREATE TABLE TEST_TABLE2 (
    TEST_1 CHAR(8) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDD')
);

CREATE TABLE TEST_TABLE3 (
    TEST_1 CHAR(10) DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD')
);

INSERT INTO TEST_TABLE3 VALUES(DEFAULT);
COMMIT;

SELECT * FROM TEST_TABLE3;