


-- CHAT =============================================================================
-- 본인이 포함되어있는 CHATROOMS 모두 조회
SELECT 
    CR.ROOM_NO, 
    CR.ROOM_NAME,
    U.USER_ID,
    U.USER_IMG, 
    TO_CHAR(CR.CREATE_DT, 'RRRR-MM-DD HH24:MM:SS') CREATE_DT, 
    CR.CREATE_USER_NO, 
    U.USER_NICKNAME, 
    U.USER_EMAIL,
    U.USER_IMG,
    (SELECT MESSAGE_CONTENT
        FROM (   
            SELECT M.MESSAGE_CONTENT
            FROM MESSAGE M
            WHERE M.ROOM_NO = CR.ROOM_NO
            ORDER BY M.SEND_TIME DESC
        ) 
        WHERE ROWNUM = 1
    ) AS LAST_MESSAGE,
    (SELECT COUNT(M.MESSAGE_NO)
        FROM MESSAGE M
        WHERE M.ROOM_NO = CR.ROOM_NO
        AND U.USER_NO = 1
        AND CRM.LAST_READ_TIME < M.SEND_TIME
    ) AS NOT_READ_CNT
FROM CHAT_ROOM_MEMBER CRM
JOIN CHAT_ROOM CR ON (CR.ROOM_NO = CRM.ROOM_NO)
JOIN USER_INFO U ON (CR.CREATE_USER_NO = U.USER_NO)
WHERE CRM.USER_NO = 1;

-- CHATROOM 안에 있는 유저 조회
SELECT 
    USER_NO, 
    USER_EMAIL, 
    USER_NICKNAME, 
    USER_IMG,
    LAST_READ_TIME
FROM CHAT_ROOM_MEMBER
JOIN USER_INFO USING(USER_NO)
WHERE ROOM_NO = 3;

-- CHATROOM 안의 메시지 조회
SELECT M.MESSAGE_NO, 
    M.MESSAGE_CONTENT, 
    M.SENDER_NO, 
    U.USER_NICKNAME SENDER_NICKNAME,
    U.USER_IMG SENDER_IMG,
    M.ROOM_NO,
    CR.ROOM_NAME,
    M.SEND_TIME
FROM MESSAGE M
JOIN USER_INFO U ON (M.SENDER_NO = U.USER_NO)
JOIN CHAT_ROOM CR ON (M.ROOM_NO = CR.ROOM_NO)
WHERE M.ROOM_NO = 2;