-- 메시지 읽음 시간 업데이트 (유저 1번이 방 1번 읽음)
UPDATE CHAT_ROOM_MEMBER SET LAST_READ_TIME = DEFAULT
WHERE ROOM_NO = 1
AND USER_NO = 1;

COMMIT;

-- 유저 권한 업데이트
UPDATE USER_INFO SET USER_AUTHORITY = 'U'
WHERE USER_NO = 5;
COMMIT;
 
-- 유저 삭제일 업데이트
UPDATE USER_INFO SET DELETE_DT = SYSDATE
WHERE USER_NO = 5;

COMMIT;

SELECT * FROM USER_INFO
WHERE USER_NICKNAME LIKE '%a%';